pre_nombres=input("ingrese pre nombres:")
primer_apellido=input("ingree su primr apellido:")
segundo_apellido=input("ingree su segundo apellido:")
nacimiento=input("ingrese la fecha se su nacimiento")
fecha_y_ubigeo=int(input("ingrese la feha y ubigeo del dni:"))
sexo="ingrese el sexo:"
fecha_de_inscripcion=input("ingrese fecha de inscrpcion:")
fecha_de_emision=input("ingrese fecha de emision:")
fecha_de_caducidad=input("ingrese fecha de caducidad")
print("###############DNI############")
print("# primer apellido:","       fecha de inscripcion:",fecha_de_inscripcion," #")
print("#",primer_apellido,"        fecha de emision:",fecha_de_emision, "#")
print("# segundo apellido:","       fecha de caducidad:",fecha_de_caducidad," #")
print("# nacimiento     fecha y ubigeo    ")
print("# ",nacimiento,"   ",fecha_y_ubigeo,"         #")
print("# sexo                                        #")
print("# ",sexo,"                                    #")
print("###############################################")